# Generated by Django 4.2.1 on 2024-05-18 23:44

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(max_length=10)),
                ('image', models.ImageField(default='default_user.jpg', upload_to='spotify/profile_pics')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='default_album.jpg', upload_to='spotify/album_pics')),
                ('release_date', models.DateField()),
                ('popularity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('followers', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('image', models.ImageField(default='default_artist.jpg', upload_to='spotify/artist_pics')),
                ('genres', models.CharField(blank=True, max_length=200)),
                ('albums', models.ManyToManyField(blank=True, related_name='artist', to='spotify.album')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('playlist_id', models.BigIntegerField()),
                ('image', models.ImageField(default='default_playlist.jpg', upload_to='spotify/playlist_pics')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('track_id', models.BigIntegerField()),
                ('popularity', models.IntegerField()),
                ('image', models.ImageField(default='default_track.jpg', upload_to='spotify/track_pics')),
                ('audio_file', models.FileField(default='default_track.mp3', upload_to='spotify/tracks')),
                ('length', models.DurationField()),
                ('albums', models.ManyToManyField(related_name='track', to='spotify.album')),
                ('artists', models.ManyToManyField(related_name='track', to='spotify.artist')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_albums', models.ManyToManyField(related_name='liked_by', to='spotify.album')),
                ('liked_artists', models.ManyToManyField(related_name='liked_by', to='spotify.artist')),
                ('liked_playlists', models.ManyToManyField(related_name='liked_by', to='spotify.playlist')),
                ('liked_tracks', models.ManyToManyField(related_name='liked_by', to='spotify.track')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='playlist', to='spotify.track'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albums', models.ManyToManyField(blank=True, related_name='library', to='spotify.album')),
                ('artists', models.ManyToManyField(blank=True, related_name='library', to='spotify.artist')),
                ('playlists', models.ManyToManyField(blank=True, related_name='library', to='spotify.playlist')),
                ('tracks', models.ManyToManyField(blank=True, related_name='library', to='spotify.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='artist', to='spotify.track'),
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='album', to='spotify.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='album', to='spotify.track'),
        ),
    ]
