# Generated by Django 4.2.1 on 2024-05-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='track', to='spotify.album'),
        ),
    ]
