# Generated by Django 4.2.1 on 2024-05-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_alter_track_albums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='playlists',
            field=models.ManyToManyField(blank=True, null=True, related_name='library', to='spotify.playlist'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked_albums',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_by', to='spotify.album'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked_artists',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_by', to='spotify.artist'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked_playlists',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_by', to='spotify.playlist'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked_tracks',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_by', to='spotify.track'),
        ),
    ]
