# Generated by Django 4.2.1 on 2024-05-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_alter_library_playlists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='audio_quality',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='autoplay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='crossfade',
            field=models.BooleanField(default=False),
        ),
    ]
